name: climpred-docs-notebooks
channels:
  - conda-forge
dependencies:
  - python >=3.9
  - bias_correction >=0.4
  - cf_xarray >=0.6.0
  - cftime >=1.5.0
  - dask-core >=2021.10.0
  - esmpy
  - esmtools >=1.1.3
  - matplotlib-base
  - nc-time-axis >=1.4.0
  - netcdf4  # ==1.5.1  # see https://github.com/pydata/xarray/issues/4925
  - pydap
  - toolz
  - xarray >=0.19.0
  - xclim !=0.30.0
  - xesmf
  - xrft
  - xskillscore >=0.0.20
  - pip
  - pip:
    - git+https://github.com/pangeo-data/climpred.git  # latest climpred version
